# Generated by Django 4.2 on 2023-06-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessSystem', '0002_signup_name_signup_number_signup_surename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
